# Generated by Django 6.0.7 on 2026-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=150)),
                ('number_of_pages', models.PositiveIntegerField(verbose_name='')),
                ('quantity', models.PositiveIntegerField(verbose_name='default=1')),
                ('available', models.PositiveIntegerField(verbose_name='default=1')),
            ],
        ),
    ]
