# Generated by Django 6.0.7 on 2026-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowtransaction',
            old_name='borrow_date',
            new_name='borrowed_date',
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
