
# Generated by Django 6.0.7 on 2026-07-21 
# Generated by Django 6.0.7 on 2026-07-25 20:50


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),

                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('joined_date', models.DateField(auto_now_add=True)),

            ],
        ),
    ]
