# Generated by Django 6.0.7 on 2026-08-08 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(default='Unknown Member', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='registration_number',
            field=models.CharField(default='REG-000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
